### ISSUE TITLE
=pf-sources-4.9_p4 not listed in manifest

### ISSUE THREAD

**Issue by beelze** [beelze/junta#4]
* A file is not listed in the Manifest: '/usr/portage/layman/junta/sys-kernel/pf-sources/pf-sources-4.9_p4.ebuild'

!!! All ebuilds that could satisfy "=pf-sources-4.9_p5" have been masked.
!!! One of the following masked packages is required to complete your request:
- sys-kernel/pf-sources-4.9_p5::junta (masked by: corruption)

**Comment by ssten** [comment]
You should *not* mix tracked and untracked ebuilds.
